# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yncyhdAtcQVTifRfVJwJz4Gl_KReQpes
"""

def calculate_grade(mark):
  if mark >= 90 and mark <= 100:
    return "A"
  elif mark >= 80 and mark <= 89:
    return "B"
  elif mark >= 70 and mark <= 79:
    return "C"
  elif mark >= 60 and mark <= 69:
    return "D"
  else:
    return "F"

mark = int(input("Enter your mark: "))
grade = calculate_grade(mark)
print("Your grade is:", grade)

def is_leap_year(year):
  if year % 400 == 0:
    print(year, "is a leap year")
  elif year % 100 == 0:
    print(year, "is not a leap year")
  elif year % 4 == 0:
    print(year, "is a leap year")
  else:
    print(year, "is not a leap year")

year = int(input("Enter a year: "))
is_leap_year(year)

def print_table(num):
  for i in range(1, 11):
    print(i, "x", num, "=", num * i)

number = int(input("Enter a number: "))
print_table(number)

def sum_n(n):
  sum = 0
  for i in range(1, n + 1):
    sum += i
  return sum

n = int(input("Enter a number: "))
print("The sum of the first", n, "natural numbers is", sum_n(n))

def factorial(n):
  fact=1
  for i in range(1, n + 1):
    fact *= i
  return fact

n = int(input("Enter a number: "))
print("The factorial of", n, "is", factorial(n))

#employee id card
emp_name=input()
emp_age=int(input())
emp_department=input()
emp_salary=float(input())
print("Name:",emp_name)
print("Age:",emp_age)
print("Salary:",emp_salary)

#grocery bill calculator
pen=10
pencil=5
scale=20
exam_pad=50
note=35
total=pen+pencil+scale+exam_pad+note
print("Total amount to be paid:",total)

#student percentage
tamil=int(input())
english=int(input())
maths=int(input())
science=int(input())
social=int(input())
total=tamil+english+maths+science+social
percentage=total/5
print("Percentage:",percentage)

#temperature converter
#celsius to fahrenheit
celsius=float(input())
fahrenheit=(celsius*9/5)+32
print("Fahrenheit:",fahrenheit)
#fafrenheit to celsius
fahrenheit=float(input())
celsius=(fahrenheit-32)*5/9
print("Celsius:",celsius)

#mobile recharge calculator
recharge_amount=int(input())
gst=int(input())
gst_percentage=(recharge_amount*gst)/100
total_amount=recharge_amount+gst_percentage
print("Total amount to be paid:",total_amount)

#ATM withdrawal
account_balance=int(input())
withdrawal_amount=int(input())
if withdrawal_amount<=account_balance:
  print("Withdrawal successful")
else:
  print("Insufficient balance")

#voting eligibility
age=int(input())
if age>=18:
  print("Eligible to vote")
else:
  print("Not eligible to vote")

#online shopping discount
total_amount=int(input())
if total_amount>=1000 and total_amount<=4999:
  discount1=(total_amount*10)/100
  print("total amount to be paid = ",total_amount-discount1)
elif total_amount>=5000:
  discount2=(total_amount*20)/100
  print("total amount to be paid = ",total_amount-discount2)
else:
  print("total amount to be paid = ",total_amount)

#login system
username=input()
password=input()
if username=="abinaya" and password=="abinaya@2006":
  print("Login successful")
else:
  print("Invalid username or password")

#el