# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jeNoApy36GMriDqjTVe1rNa_YfkXbLl
"""

#variables
name="abinaya"
age=20
height=157.5
print(id(name))
print(id(age))
print(id(height))

#keywords
help("keywords")

#data types
name="abinaya"
age=20
height=157.5
c=2+4j
d=True
print(type(name))
print(type(age))
print(type(height))
print(type(c))
print(type(d))

#arithmatic operator
a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

#assignment operator
a=10
print(a)

#relational operator
age1=25
age2=20
print(age1==age2)
print(age1!=age2)
print(age1>age2)
print(age1<age2)
print(age1>=age2)
print(age1<=age2)

#logical operator
x=5
print(x>3 or x>10)
print(x>3 and x>10)
print(not x>10)

#identity operator
a=("abinaya","kovarshini")
b=("abinaya","kovarshini")
print(a is b)
print(a is not b)

#membership operator
a=("abinaya","kovarshini")
b=("abinaya","kovarshini")
print("abinaya" in a)
print("abinaya" not in b)

#if-else
age=int(input("enter your age: "))
if age>=18:
  print("you are eligible for voting")
else:
  print("you are not eligible for voting")
print("success")

#elif
series=input("enter the series name: ")
if series=="all of us dead":
  print("watch")
elif series=="stranger things":
  print("fine...watch")
else:
  print("search something else")

#nested if
age=int(input("enter your age: "))
weight=int(input("enter your weight: "))
if age>=18:
  if weight>=50:
    print("eligible for blood donation")
  else:
    print("low weight... you are not eligible")
else:
  print("less age for blood donation")

#loop
for i in range(10):
  print(i)
print("loop ended")

#loop in range
for i in range(0,10,2):
  print(i)

for i in range(0,100,3):
  print(i)

for i in range(100,0,-3):
  print(i)